#############################################################################
# Makefile for building: iC3SSLClient
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Nov 2 04:08:39 2016
# Project:  iC3SSLClient.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile iC3SSLClient.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Iqcustomplot -Idatabase -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		client.cpp \
		QtJson.cpp \
		qcustomplot/qcustomplot.cpp \
		database/iC3_DatabaseTable.cpp \
		database/iC3_Database.cpp \
		database/iC3_DMM_UtilityFunctions.cpp \
		database/iC3_DatabaseColumnDef.cpp \
		database/iC3_TransducerTable.cpp moc_client.cpp \
		moc_qcustomplot.cpp \
		moc_iC3_DatabaseTable.cpp \
		moc_iC3_Database.cpp \
		moc_iC3_DMM_UtilityFunctions.cpp \
		moc_iC3_DatabaseColumnDef.cpp
OBJECTS       = main.o \
		client.o \
		QtJson.o \
		qcustomplot.o \
		iC3_DatabaseTable.o \
		iC3_Database.o \
		iC3_DMM_UtilityFunctions.o \
		iC3_DatabaseColumnDef.o \
		iC3_TransducerTable.o \
		moc_client.o \
		moc_qcustomplot.o \
		moc_iC3_DatabaseTable.o \
		moc_iC3_Database.o \
		moc_iC3_DMM_UtilityFunctions.o \
		moc_iC3_DatabaseColumnDef.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		iC3SSLClient.pro
QMAKE_TARGET  = iC3SSLClient
DESTDIR       = 
TARGET        = iC3SSLClient

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_client.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: iC3SSLClient.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile iC3SSLClient.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile iC3SSLClient.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/iC3SSLClient1.0.0 || $(MKDIR) .tmp/iC3SSLClient1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/iC3SSLClient1.0.0/ && $(COPY_FILE) --parents client.h QtJson.h qcustomplot/qcustomplot.h database/iC3_DatabaseTable.h database/iC3_Database.h database/iC3_DMM_UtilityFunctions.h database/iC3_DatabaseColumnDef.h database/iC3_DMM_Constants.h database/iC3_TransducerTable.h .tmp/iC3SSLClient1.0.0/ && $(COPY_FILE) --parents main.cpp client.cpp QtJson.cpp qcustomplot/qcustomplot.cpp database/iC3_DatabaseTable.cpp database/iC3_Database.cpp database/iC3_DMM_UtilityFunctions.cpp database/iC3_DatabaseColumnDef.cpp database/iC3_TransducerTable.cpp .tmp/iC3SSLClient1.0.0/ && $(COPY_FILE) --parents client.ui .tmp/iC3SSLClient1.0.0/ && (cd `dirname .tmp/iC3SSLClient1.0.0` && $(TAR) iC3SSLClient1.0.0.tar iC3SSLClient1.0.0 && $(COMPRESS) iC3SSLClient1.0.0.tar) && $(MOVE) `dirname .tmp/iC3SSLClient1.0.0`/iC3SSLClient1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/iC3SSLClient1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_client.cpp moc_qcustomplot.cpp moc_iC3_DatabaseTable.cpp moc_iC3_Database.cpp moc_iC3_DMM_UtilityFunctions.cpp moc_iC3_DatabaseColumnDef.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_client.cpp moc_qcustomplot.cpp moc_iC3_DatabaseTable.cpp moc_iC3_Database.cpp moc_iC3_DMM_UtilityFunctions.cpp moc_iC3_DatabaseColumnDef.cpp
moc_client.cpp: QtJson.h \
		client.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) client.h -o moc_client.cpp

moc_qcustomplot.cpp: qcustomplot/qcustomplot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcustomplot/qcustomplot.h -o moc_qcustomplot.cpp

moc_iC3_DatabaseTable.cpp: database/iC3_DatabaseColumnDef.h \
		database/iC3_DMM_Constants.h \
		database/iC3_DMM_UtilityFunctions.h \
		database/iC3_DatabaseTable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) database/iC3_DatabaseTable.h -o moc_iC3_DatabaseTable.cpp

moc_iC3_Database.cpp: database/iC3_DMM_Constants.h \
		database/iC3_TransducerTable.h \
		database/iC3_DatabaseTable.h \
		database/iC3_DatabaseColumnDef.h \
		database/iC3_DMM_UtilityFunctions.h \
		database/iC3_Database.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) database/iC3_Database.h -o moc_iC3_Database.cpp

moc_iC3_DMM_UtilityFunctions.cpp: database/iC3_DMM_Constants.h \
		database/iC3_DMM_UtilityFunctions.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) database/iC3_DMM_UtilityFunctions.h -o moc_iC3_DMM_UtilityFunctions.cpp

moc_iC3_DatabaseColumnDef.cpp: database/iC3_DatabaseColumnDef.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) database/iC3_DatabaseColumnDef.h -o moc_iC3_DatabaseColumnDef.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_client.h
compiler_uic_clean:
	-$(DEL_FILE) ui_client.h
ui_client.h: client.ui
	/usr/bin/uic-qt4 client.ui -o ui_client.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp client.h \
		QtJson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

client.o: client.cpp client.h \
		QtJson.h \
		ui_client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

QtJson.o: QtJson.cpp QtJson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtJson.o QtJson.cpp

qcustomplot.o: qcustomplot/qcustomplot.cpp qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot/qcustomplot.cpp

iC3_DatabaseTable.o: database/iC3_DatabaseTable.cpp database/iC3_DatabaseTable.h \
		database/iC3_DatabaseColumnDef.h \
		database/iC3_DMM_Constants.h \
		database/iC3_DMM_UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iC3_DatabaseTable.o database/iC3_DatabaseTable.cpp

iC3_Database.o: database/iC3_Database.cpp database/iC3_Database.h \
		database/iC3_DMM_Constants.h \
		database/iC3_TransducerTable.h \
		database/iC3_DatabaseTable.h \
		database/iC3_DatabaseColumnDef.h \
		database/iC3_DMM_UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iC3_Database.o database/iC3_Database.cpp

iC3_DMM_UtilityFunctions.o: database/iC3_DMM_UtilityFunctions.cpp database/iC3_DMM_UtilityFunctions.h \
		database/iC3_DMM_Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iC3_DMM_UtilityFunctions.o database/iC3_DMM_UtilityFunctions.cpp

iC3_DatabaseColumnDef.o: database/iC3_DatabaseColumnDef.cpp database/iC3_DatabaseColumnDef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iC3_DatabaseColumnDef.o database/iC3_DatabaseColumnDef.cpp

iC3_TransducerTable.o: database/iC3_TransducerTable.cpp database/iC3_TransducerTable.h \
		database/iC3_DatabaseTable.h \
		database/iC3_DatabaseColumnDef.h \
		database/iC3_DMM_Constants.h \
		database/iC3_DMM_UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iC3_TransducerTable.o database/iC3_TransducerTable.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_iC3_DatabaseTable.o: moc_iC3_DatabaseTable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iC3_DatabaseTable.o moc_iC3_DatabaseTable.cpp

moc_iC3_Database.o: moc_iC3_Database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iC3_Database.o moc_iC3_Database.cpp

moc_iC3_DMM_UtilityFunctions.o: moc_iC3_DMM_UtilityFunctions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iC3_DMM_UtilityFunctions.o moc_iC3_DMM_UtilityFunctions.cpp

moc_iC3_DatabaseColumnDef.o: moc_iC3_DatabaseColumnDef.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iC3_DatabaseColumnDef.o moc_iC3_DatabaseColumnDef.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

